name: sqlite
version: 0.5.0
description: SQLite bindings for Dart
homepage: https://github.com/pylaligand/dart-sqlite
authors:
  - Sam McCall
  - P.Y. Laligand
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  args: ^1.5.0
  http: ^0.12.0
  path: ^1.6.2
  yaml: ^2.1.15
dev_dependencies:
  test: ^1.3.4
